### ISSUE TITLE
Use Github Language colors for the graph

### ISSUE THREAD

**Issue by Ombrelin** [LacazeThomas/wakapi-stats#27]
Hello,
Thank you for this awesome tools which is much nicer than the base solution offered by wakapi.

I think it would be neat though if of random colors, the same colors used by github to describe a repository's languages were displayed on the graph.

Use the following JSON file which contains the needed data : 

https://github.com/ozh/github-colors/blob/master/colors.json

Thank you in advance !

**Comment by LacazeThomas** [comment]
Hello, 
Thank you for your support. 

It is under development, the release will be coming soon !

Thank you
